#!/bin/csh -f

source ./a2-setup

if ($have_lseek) then
  # Ignore messages about syscall 68 (remove) not implemented.
  echo "Ignore messages: Unknown syscall 68 (remove)"
  sys161 kernel "p testbin/badcall b;q"
else
  echo "This test is skipped because it requires lseek"
endif
